// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHMOH-f6CSDyPICsxiynLvCY2-djGZvm8',
    appId: '1:217167511944:web:10b3147b45bf02b974fa3d',
    messagingSenderId: '217167511944',
    projectId: 'crew-portal-dev',
    authDomain: 'crew-portal-dev.firebaseapp.com',
    databaseURL: 'https://crew-portal-dev-default-rtdb.firebaseio.com',
    storageBucket: 'crew-portal-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvJKx2EzRtUL8EFu_RltYFUA6L0u_rjys',
    appId: '1:217167511944:android:221b043f48f448ca74fa3d',
    messagingSenderId: '217167511944',
    projectId: 'crew-portal-dev',
    databaseURL: 'https://crew-portal-dev-default-rtdb.firebaseio.com',
    storageBucket: 'crew-portal-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdAQLfPd1nDC7HAAKvyqOa9apMSoPTMYU',
    appId: '1:217167511944:ios:a8b0e64f917dee8174fa3d',
    messagingSenderId: '217167511944',
    projectId: 'crew-portal-dev',
    databaseURL: 'https://crew-portal-dev-default-rtdb.firebaseio.com',
    storageBucket: 'crew-portal-dev.appspot.com',
    iosClientId: '217167511944-0bgjkhrqj1otsr5qutbi2051i1ue183d.apps.googleusercontent.com',
    iosBundleId: 'com.example.crewPortalDev',
  );
}
